### ISSUE TITLE
 Problem with cyrilllic

### ISSUE THREAD

**Issue by dddyom** [monkoose/neocodeium#10]
### 👎 Problem

Hi again!

I describe problems with the Cyrillic alphabet. When calling `neocodeium.accept`, some letters are skipped and must be entered manually. Although in virtual text the addition is correct

### Before calling accept
![2024-05-23_15-56_1](https://github.com/monkoose/neocodeium/assets/59733683/b7de1630-6f26-46c1-aeb5-603fa96d4dca)
### After
![2024-05-23_15-56](https://github.com/monkoose/neocodeium/assets/59733683/7ebd0b64-4893-4d67-823a-8fcb207f1b27)

### 🔢 Steps to reproduce

To reproduce this, you need to initiate a hint by writing any word in Cyrillic (for example, "привет"). Then call the `accept`.

When writing **“Привет,”** neocodeium adds the word **“мир”** to the virtual text, but after calling `accept`, only **“ми”** is added

### 👍 Expected behavior

Correct addition

Thanks for your time!

### Neovim version (nvim -v)

nightly

### Operating system (uname -om)

Linux x86_64

### :checkhealth neocodeium

OK

**Comment by monkoose** [comment]
Reproduced.

**Comment by monkoose** [comment]
An obvious issue is that letters are "eaten up" after cyrillic `р`.

**Comment by monkoose** [comment]
Should be fixed.
