### ISSUE TITLE
Disable while recording macro

### ISSUE THREAD

**Issue by chrisgrieser** [monkoose/neocodeium#11]
### Problem

When recording a macro, neocodium still makes suggestions. It's a bit distracting, especially since you would not want to use AI suggestions during a recording anyway.

It's possible to automatically enable/disable Neocodium via autocommand, but a plugin-side solution is probably cleaner.

### Expected behavior

Automatically disable neocodium while recording a macro. Potentially make this an option? (though I personally cannot really think of a case where you'd want AI suggestions while recording.)

**Comment by monkoose** [comment]
Hello.
I'm not sure if it is really necessary, because it actually can be useful and completion is works with macros. so it's no hard default for me then.

Maybe provided example in the documentation/readme is better solution? So users who would find it disctracted as you can just copy/paste it.
