### ISSUE TITLE
could you please add an option to disable all filetypes except the few I enable in the filetypes table

### ISSUE THREAD

**Issue by gaven140** [monkoose/neocodeium#13]
### Problem

An option to disable for all filetypes except the ones I explicitly enable in the filetypes table.

### Expected behavior

```lua
filetypes = {
  all = false,
  lua = true,
  python = true,
  ...
}


-- OR
filetypes_disable_all = true,
filetypes = {
  -- filetypes to enable
}
```

**Comment by monkoose** [comment]
I have implemented possibility for `enabled` option to be a function.
So you can implement whatever logic you want to disable in specific buffer or another required situations (like for whole privacy required projects etc).

For your request it would be something like
```lua
local filetyps = { 'lua', 'python' }
neocodeium.setup({
   -- function accepts one argument `bufnr`
   enabled = function(bufnr)
      if vim.tbl_contains(filetypes, vim.api.nvim_get_option_value('filetype',  { buf = bufnr})) then
         return true
      end
   return false
   end
})
```
