### ISSUE TITLE
[Bug] Suggestions never appear

### ISSUE THREAD

**Issue by Ajaymamtora** [monkoose/neocodeium#14]
### 👎 Problem

No matter what I do the suggestions never appear, ive tried enabled = true, false, cycling completions manually etc and im definitely logged in with my API key.

Ive also restarted the server and ran the other enable ex commands.

### 🔢 Steps to reproduce

I'm using mostly the default setup.

### 👍 Expected behavior

Suggestions should appear

### Neovim version (nvim -v)

Stabled 0.10

### Operating system (uname -om)

macOS arm64

### :checkhealth neocodeium

OK

### Relevant log output

```shell
No log appears no matter what.
```

**Comment by monkoose** [comment]
Hello, could you run neovim with `NEOCODEIUM_LOG_LEVEL=info nvim
` and paste the log here.

**Comment by monkoose** [comment]
Sorry, seems like I can't fix this from plugin side. 
Something with this log lines. Not sure why codeium error on this. I know chezmoi cli tool, but why it interacts work codeium in such way?

> Wraps: (5) read /Users/SCRUBBED/.local/share/chezmoi
Wraps: (6) is a directory

 From my head it could be two issues: 
 1. Problem with codeium language server itself, would require some testing from your side. You can try different codeium language server yourself, find it's versions here https://github.com/Exafunction/codeium and just change this line https://github.com/monkoose/neocodeium/blob/4a46f6438bcdb21c562f83036bce75c719834072/lua/neocodeium/binary.lua#L18 to this new version.
 3. Problem with your setup/OS. I can't help there

**Comment by monkoose** [comment]
Glad to hear it.
Which version do you use exactly? For some time I will update it to this version and will consider to add a such option in the future.

**Comment by monkoose** [comment]
Thanks, I have bumped the version.

**Comment by monkoose** [comment]
@Ajaymamtora it totally get skipped from my mind that you can download any specific codeium server binary from https://github.com/Exafunction/codeium/tags, extract it and specify the path to it in `neocodeium.setup({ bin = 'path/to/binary' })`

So adding new option for specific codeium server number is maybe a little bit more convenient, but at the same time redundant.

**Comment by monkoose** [comment]
I don't think it is a good idea. For example you can try last version 1.16.1 and neocodeium would not work, because they have changed something internally (should investigate what exactly). And the worst codeium doesn't have any documentation, api reference etc.
