### ISSUE TITLE
Add command/function for status

### ISSUE THREAD

**Issue by edshamis** [monkoose/neocodeium#15]
### Problem

I'd like to have an ability to know if NeoCodeium is enabled in general and for current buffer, for example to set statusline

### Expected behavior

I propose two new command (and corresponding lua functions)
:NeoCodeium status
:NeoCodeium status_buffer

**Comment by monkoose** [comment]
Hello, I'm planning to update get_status() function to return some numeric values the reason of disabled status.
0 - enabled, 1 - globally disabled, 2 - disabled in a buffer, 3 - disabled with options.filetypes, 4 - disabled with options.enabled() function.

I will notify you when it would be done.

**Comment by monkoose** [comment]
@edshamis Done.
You can check the more info here https://github.com/monkoose/neocodeium?tab=readme-ov-file#-statusline
