### ISSUE TITLE
Hooks on displaying hint

### ISSUE THREAD

**Issue by mehalter** [monkoose/neocodeium#21]
### Problem

In the provided example for using NeoCodeium alongside `nvim-cmp` it shows the case for having automatic autocompletion on for NeoCodeium and disabling auto completion for `nvim-cmp`. For this it utilizes adding a hook for when the `nvim-cmp` menu opens to clear the NeoCodeium completion.

This is a very nice approach for that case, but it would be really beautiful to support the inverse case where `manual = true` for NeoCodeium and autocompletion is enabled for `nvim-cmp`. Then if a hint is displayed for NeoCodeium then we can have a hook that closes `nvim-cmp` if it is visible.

One option is to just add it before calling the `cycle` or `cycle_or_complete` functions but if the binding is pressed and no completion actually comes from NeoCodeium for whatever reason it would be preferred to not close the `nvim-cmp` suggestion if it's open, it should wait until something actually wants to get displayed as virtual text.

### Expected behavior

We could have a hook function option in the NeoCodeium setup to allow running code such as (I'm really no sold on the name of this option or function, just for example sake):

```lua
require("neocodeium").setup({
  on_hint = function()
    require("cmp").abort()
  end
})

**Comment by monkoose** [comment]
Will not add this. Sorry.

**Comment by mehalter** [comment]
No problem! Just a suggestion 😄

**Comment by mehalter** [comment]
It might be a good idea to close this issue as "Not Planned" rather than completed

**Comment by monkoose** [comment]
Yes, thanks.

**Comment by monkoose** [comment]
As a follow up question, is there any reason why you don't use `codeium.nvim` if you want good nvim-cmp integration? It would require the same amount of actions from the user to get codeium suggestions.

**Comment by mehalter** [comment]
I just really don't like AI suggestions all the time over just normal code completion from LSP. I prefer to have it manual where if I have something that I want to throw at it I can and then it would close my cmp completion (as it's not providing anything AI related and it just covers up the virtual text) and then I can cycle through some suggestions. Then after accepting or rejecting suggestions I go back to my normal editing

**Comment by mehalter** [comment]
I wonder if my original question was poorly worded if you think that I _want_ `nvim-cmp` integration 🤔

**Comment by mehalter** [comment]
> Personally I have found that I type much more less with codeium suggestions, rather then with default autocompletion tools. Have you tried this approach lets say for a day or so?

Not all of the code I work with _can_ be passed to any sort of cloud provider AI tool due to licensing/security reasons. I also find that AI completion tends to be pretty wrong a lot of the time so I typically rely on my own programming ability as it seems to be more stable and reliable. Then when I'm bored and want to toy around then I may want to throw a random thing at it.

**Comment by monkoose** [comment]
> Not all of the code I work with can be passed to any sort of cloud provider AI tool due to licensing/security reasons

Understandable.

> I also find that AI completion tends to be pretty wrong a lot of the time

Not my experience. And when they are I can manually invoke autocompletion with one shortcut, but safe like 20-100 next time its suggestion is helpful.

I have not tried, but maybe something like this could work?
```lua
require("neocodeium").setup({
    enabled = function()
        return not cmp.visible()
    end
})

And create additional shortcut, that will close cmp window and after that run `neocodeium.cycle_or_complete()`?
```
The worst part of it that it would send request to the server only after `cycle_or_complete()` and will take some time.
It's best what I can think of, other than that I definitely not planning to add such feature.

**Comment by mehalter** [comment]
Ok, have you ever considered adding autocommand events when things happen? Like just when a request is successful or a completion is rendered to trigger a User autocommand event? Seems like it would just be a single line at each point where an event could be triggered and then it would add points where the user could add hooks into things 🤔  This is the "vim" way of doing stuff like this and would be highly generalizable for 0 cost.

If you are open to it, I can also put together a PR that achieves this in the next week or 2 since it's basically no code and would just take me reading through and understanding the code to find logical places to put it.

**Comment by monkoose** [comment]
> Ok, have you ever considered adding autocommand events when things happen? Like just when a request is successful or a completion is rendered to trigger a User autocommand event?

There is no point in it if `neocodeium is in disabled state` - it would never send any request and so never trigger such autocommands.

And it actually has cost. It complecates stuff, shifts the burden to the user, who can add some heavy logic to this autocommands and complain that plugin is slow.
You are free to fork and add whatever you want for sure:)

**Comment by mehalter** [comment]
Ok, when you say I'm free to fork and do whatever, does that mean you are open to pull requests and contributions or nah? If not that's totally fine, just curious what the culture is here 😄

**Comment by monkoose** [comment]
I'm open for PR's, but not for this feature. Sorry.

**Comment by monkoose** [comment]
@mehalter Would it be too much to ask you to check and to fix grammar in the readme? I want to make it too look a little bit more professional, and I know how it represented badly in my mother tongue, when I read a text with a lot of mistakes.
If you do, then it doesn't need to be extreme to fully change whole sentences, just to fix wrong grammar. Because even AI and grammar checkers not so good for this.

**Comment by mehalter** [comment]
Oh yeah, I can definitely do that! I should be able to sometime today in between work stuff
