### ISSUE TITLE
Default keybinds are not guaranteed to work on MacOS

### ISSUE THREAD

**Issue by jnsahaj** [monkoose/neocodeium#22]
### 👎 Problem

Reproducible on `main`

This is not really a bug with the plugin but general issue with macOS. The "Alt" or "Opt" key on MacOS don't work as expected as vim/nvim keybinds. The terminal on mac doesn't send the meta key modifier when using Alt. To be honest, the behaviour is not consistent across different terminal emulators. 

My setup:
iTerm2, zsh, tmux, nvim 0.10.1, lazy.nvim

references
https://stackoverflow.com/questions/7501092/can-i-map-alt-key-in-vim
https://github.com/alacritty/alacritty/issues/62

### 🔢 Steps to reproduce

Configure `"<A-f>"` as a keybind on macOS terminal for vim or nvim.

### 👍 Expected behavior

neocodeium.accept() should run (simplified: `"<A-f>"` should get triggered)

### Neovim version (nvim -v)

0.10.1

### Operating system (uname -om)

macOS arm64

### :checkhealth neocodeium

OK

**Comment by monkoose** [comment]
There is no default keybindings. It is just example. You can map whatever keybindings suit or work for you.
Closed.
