### ISSUE TITLE
New codeium server binaries are broken

### ISSUE THREAD

**Issue by monkoose** [monkoose/neocodeium#24]
### 👎 Problem

Starting from v1.14.13 opening chat will end up with `E0910 08:49:31.198921  6805 interceptor.go:49] /exa.language_server_pb.LanguageServerService/AddTrackedWorkspace: file:///path/to/project/root/dir is hidden: ignore uri` 
Seems like this isn't possible to fix from neocodeium side.

Currently the last [v.1.16.1](https://github.com/Exafunction/codeium/releases/tag/language-server-v1.16.1) is totally broken, so autocompletion doesn't work either. Error is `E0910 08:54:27.140749  7487 interceptor.go:49] /exa.language_server_pb.LanguageServerService/GetCompletions: must set either FileAbsolutePath or CorpusRootRelPath`
This maybe fixable but definitely requires some exploration what is `FileAbsolutePath` and `CorpusRootRelPath` is this some new requests, or GetCompletions request expects this new values?

Meanwhile frozen on v1.14.12 for these reasons.

**Comment by aliaksandr-trush** [comment]
This commit should help you https://github.com/Exafunction/codeium.nvim/commit/f74f999ec5b383dc7a67c0298051ec2be2b17cab

**Comment by monkoose** [comment]
Thanks.

**Comment by monkoose** [comment]
Thanks again. I have fixed this issues and updated codeium language server to the last version.
