### ISSUE TITLE
Show number of suggestions

### ISSUE THREAD

**Issue by kingedward35** [monkoose/neocodeium#33]
### Problem

I was previously using the `codeium.vm` plugin and there is a way to show the number of suggestions in the lualine plugin. I was wondering if this also available in this plugin? Thanks.

### Expected behavior

If possible, is there a way to see the number of suggestions in a status line? Thanks.

**Comment by monkoose** [comment]
They are shown at number column.

**Comment by kingedward35** [comment]
I see them now. Don't know how I missed that. Thanks.
