### ISSUE TITLE
label is breaking renaming with lsp in dressing.nvim

### ISSUE THREAD

**Issue by H4ckint0sh** [monkoose/neocodeium#34]
### 👎 Problem

the label if is activated showing in input in dressing.nvim file rename ui and blocking some characters.

<img width="459" alt="Screenshot 2024-09-13 at 16 36 40" src="https://github.com/user-attachments/assets/dc22354f-617c-4224-87b4-8b414cd8414d">

### 🔢 Steps to reproduce

Install neododeium alongside dressing.nvim and enable label.

### 👍 Expected behavior

No label visible.

### Neovim version (nvim -v)

0.10.1

### Operating system (uname -om)

macOS arm64

### :checkhealth neocodeium

OK

**Comment by monkoose** [comment]
Disable neocodeium for such windows.

**Comment by monkoose** [comment]
I don't know your neovim expertise, so if something is unclear, feel free to continue asking in this issue.

**Comment by H4ckint0sh** [comment]
I consider myself a noob but I thought that maybe the plugin was not meant to run in such places.

**Comment by monkoose** [comment]
Places like what? Everything in neovim is windows and buffers.

**Comment by H4ckint0sh** [comment]
Thants an vim.ui.input and I has no file type. It returns either a string that user has put in or nil. So haw do i disable neocodeium there?

**Comment by monkoose** [comment]
> Thats an vim.ui.input 

Not this is not. It is custom implementation made with floating window and buffer.

https://github.com/stevearc/dressing.nvim/blob/c5775a888adbc50652cb370073fcfec963eca93e/lua/dressing/input.lua#L438

**Comment by H4ckint0sh** [comment]
Yea I saw it too in the source. I have to learn more about Neovim. 
Whats important is that it is in fact working as I want it. Tanks again.

**Comment by zhou13** [comment]
@monkoose It would be helpful to make this default:
```
      neocodeium.setup {
        filetypes = {
          DressingInput = false,
        },
      }
```
It can save people from one extra google search :)

**Comment by monkoose** [comment]
"DressingInput" is not neovim default filetype. I suppose it is some external plugin. Not all the users use it. So my answer is no.
Example how to use `filetypes` option is documented. User can add any additional plugin's filetypes they want.
