### ISSUE TITLE
NeoCodeium: failed to extract binary on enterprise

### ISSUE THREAD

**Issue by LeonardoMor** [monkoose/neocodeium#35]
### 👎 Problem

This is because my company portal is not hosting the language server binary. At least with the URL structure that is expected by neocodeium. 

So downloading the binary:
```output
❯ curl -Lo language_server_linux_x64.gz https://codeium.company.net/language-server-v1.14.12/language_server_linux_x64.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7452    0  7452    0     0   7494      0 --:--:-- --:--:-- --:--:--  7489
```

Would seem like it succeeded. But what's downloaded is in fact an HTML file saying that the page doesn't exist:
```output
❯ gunzip -t language_server_linux_x64.gz; echo $?

gzip: language_server_linux_x64.gz: not in gzip format
1
❯ file language_server_linux_x64.gz
language_server_linux_x64.gz: HTML document, ASCII text, with very long lines (7452), with no line terminators
```

So, it'd be good if there's some fallback mechanism. If what's downloaded is not a gzip file, then download from somewhere else. This can be the URL formed with `https://github.com/Exafunction/codeium/releases/download`. For what is worth `codeium.vim` uses:

https://github.com/Exafunction/codeium.vim/blob/fa65fa942aaf1aef73b6dbe3cc0faa713b738fbe/autoload/codeium/server.vim#L203

### 🔢 Steps to reproduce

Configure neocodeium, populating `server.api_url` and `server.portal_url`. Then use it.

### 👍 Expected behavior

I would expect a gz file containing the binary to be downloaded and the extraction to succeed.

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system (uname -om)

Linux x86_64

### :checkhealth neocodeium

Error

### Relevant log output

```shell
neocodeium: require("neocodeium.health").check()

System information: ~
- *linux* *(x64)*
  If it is not correctly detected, then consider to report a bug at
  https://github.com/monkoose/neocodeium/issues

Checks: ~
- OK *curl* is installed
- OK *API* *key* is present
- ERROR *Server* *binary* is missing   <<< Relevant
- ERROR *Server* has not been started  <<< Relevant
```
```

**Comment by monkoose** [comment]
Thanks for detailed investigation.

Personally, I don't have access to enterprise, so code for it support was adapted from codeium.vim.
Not sure if I wan't to fix this myself without a PR from the user with actual enterprise access. Or else it would be the same as finding a needle in a haystack. I was even thinking of removing enterprise support and leaving its support to codeium.vim.

If you do know actual download link, then You can download and extract it manually and set `setup.bin = 'path/to/it'`.

Did `:NeoCodeium auth` work? Did it persist in `~/.codeium/config.json`?

> So, it'd be good if there's some fallback mechanism. If what's downloaded is not a gzip file, then download from somewhere else. This can be the URL formed with https://github.com/Exafunction/codeium/releases/download.

Would it still work with the enterprise api key?

**Comment by LeonardoMor** [comment]
That's a good point.

I downloaded the binary from the GitHub link and the api key was successfully saved to the expected place. But even after that, it doesn't work. I see a lot of these in the logs:
```
E0914 15:01:05.306250 697792 api_server_client.go:277] GetConfig error: 404 Not Found
E0914 15:01:06.470855 697792 api_server_client.go:277] GetConfig error: 404 Not Found
E0914 15:01:07.615582 697792 api_server_client.go:277] GetConfig error: 404 Not Found
E0914 15:01:08.896268 697792 api_server_client.go:277] GetConfig error: 404 Not Found
E0914 15:01:10.040888 697792 api_server_client.go:277] GetConfig error: 404 Not Found
E0914 15:01:11.321894 697792 api_server_client.go:277] GetConfig error: 404 Not Found
E0914 15:01:12.469890 697792 api_server_client.go:277] GetConfig error: 404 Not Found
```

I'll see if I can do something about this.

**Comment by monkoose** [comment]
Does codeium.vim or codeium.nvim work for you?
For temporal workaround you can use one of them to download the binary and then specify path to it.

**Comment by LeonardoMor** [comment]
I used to use codeium.vim and it works.

But the error suggests it is failing to retrieve config, no? I'll do some tests. We'll see.

**Comment by monkoose** [comment]
The question is how do you even know about portal_url option on codeium.vim when it is not documented anywhere? Or how other enterprise users have found it?

**Comment by LeonardoMor** [comment]
Because codeium gives enterprise users instructions on how to set it up.

One correction, the latest commit of codeium.vim doesn't work for me. It fails to download the language server. Which might be the same issue I'm hitting with neocodeium.

I'll do a little more testing.

**Comment by LeonardoMor** [comment]
I think I found the bug:

https://github.com/monkoose/neocodeium/blob/8608ec3ef7bdac5a667a87eefba8137370990029/lua/neocodeium/server.lua#L72

On debug logs I see this:
```
I0914 18:15:35.341499 1233243 client.go:589] [DEBUG] GET https://codeium.company.net/_route/api_server%20--enterprise_mode/exa.api_server_pb.ApiServerService/GetCompletions
```

`%20--enterprise_mode` should not be there in the URL.

**Comment by LeonardoMor** [comment]
So replacing that part with:
```lua
   local args = {
      "--api_server_url",
      api_url or "https://server.codeium.com",
      "--manager_dir",
      manager_dir,
   }

   if options.server.api_url and options.server.api_url ~= "" then
      table.insert(args, "--enterprise_mode")
   end

   if options.server.portal_url and options.server.portal_url ~= "" then
      table.insert(args, "--portal_url")
      table.insert(args, options.server.portal_url)
   end
```
Makes this the plugin work.

But only if I manually pass the binary. So that still needs fixing.

**Comment by monkoose** [comment]
Can you share codeium enterprise instructions how to configure it, without some private urls (if any) and without irrelevant or privacy concerned parts?

In codeium.vim I can see usage of "sha" variable which you can add to `config.json` and it would try to download enterpise binary with this "sha", and not specific version. Which is currently not processed in your PR.

**Comment by LeonardoMor** [comment]
Sure I'll add the enterprise instructions.

I'll check more about the sha and edit accordingly.

**Comment by LeonardoMor** [comment]
In other places, like with their emacs thing, they only use the github url. Given that, it will be better to just go and download the binary straight from the github url the way it is done for emacs.

If users want to use a different binary, they can download and extract it manually and then use it with the `bin` option that you already implemented.

Would you be okay with doing it this way?

**Comment by monkoose** [comment]
I don't mind, for some reason I have thought that they share to Enterprise users some custom binaries, if there is no difference, then I don't care much, just asked. 

Can you test pending comment in the PR, because I think that it never resets the download link without `:wait()`.

**Comment by LeonardoMor** [comment]
I think that doesn't apply anymore. Please see the commits now. Let me know if you would like anything changed.

For what is worth, now both enterprise and normal Codeium work with this plugin with these changes.

**Comment by monkoose** [comment]
Ok, will check a little bit later. Thanks for your help.

**Comment by LeonardoMor** [comment]
Thank you for the awesome plugin this is so well made, it's so satisfying to see.
