### ISSUE TITLE
Bug: `show_label = false` not respected

### ISSUE THREAD

**Issue by chrisgrieser** [monkoose/neocodeium#38]
### 👎 Problem

Even though I have set `show_label = false`,  neocodium will *sporadically* still display ` 0 ` in the signcolumn. 

![Pasted image 2024-10-16 at 16 19 09@2x](https://github.com/user-attachments/assets/be4da653-5b65-48d1-844b-e2b227a89ff6)

As opposed to the regular behavior of `show_label = true`, this happens even though I have disabled line numbers disabled via `vim.opt.number = false`, so it apparently adds the label to the signcolum instead of the number column or something like that.

### 🔢 Steps to reproduce

I unfortunately cannot reproduce it reliably. The issue only occurs sporadically, with no specific pattern I noticed. It might only occur during specific moments when the client is connecting or something, but that's just a guess.

### 👍 Expected behavior

`show_label = false` should be respected.

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system (uname -om)

macOS arm64

### :checkhealth neocodeium

OK

**Comment by monkoose** [comment]
Thanks for reporting.
I have discovered some weird behavior of the label too, but a little bit opposite (Even when it is true in some rare cases it doesn't show up). I will try to investigate it closely maybe on this weekend.

**Comment by monkoose** [comment]
Last commit should fix it. But not the issue of disappeared label on some occasions.

**Comment by chrisgrieser** [comment]
Thank you!

**Comment by monkoose** [comment]
I will close this for now. And will create a new issue later (maybe).
I have tried to find a solution for mine described issue, but haven't found any logic problems in the code itself. Maybe it is more upstream issue how neovim handles virtual text with scheduled functions. And this issue not so important, because plugin still works.
