### ISSUE TITLE
Doesn't work in .go files

### ISSUE THREAD

**Issue by octaviusz** [monkoose/neocodeium#5]
Doesn't work in files with `.go` filetype, but at the same time works perfectly well and produces golang code in files with `.mod`.

**Comment by monkoose** [comment]
This isn't descriptive enough and not reproducible. At least provide some context.
Does `:checkhealth neocodeium` shows any errors?

**Comment by octaviusz** [comment]
oh never mind it was my config problem.

**Comment by Kypert** [comment]
@octaviusz, thanks, it seems you are right, but I do not understand why it is conflicting. Did you solve running them side-by-side or just ripped vim-sleuth out?

**Comment by octaviusz** [comment]
@Kypert I disabled `tpope/vim-sleuth`

**Comment by monkoose** [comment]
I guess this is because vim-sleuth changes `'fileencoding'` and codeium server accepts only utf-8 and latin1 encodings, so it is disabled otherwise. Could you check what `'fileencoding'` option is after vim-sleuth changes it in go filetyped?

**Comment by Kypert** [comment]
With `tpope/vim-sleuth`, it looks like the .go-file stays with `fileencoding=utf-8`, NeoCodeium is also happy:
```
:lua print(require("neocodeium").get_status())
0 0
```
Also checked `fileencodings=ucs-bom,utf-8,default,latin1`, it also stays the same.

Setting `vim.g.sleuth_heuristics = 0` is also a way to get NeoCodeium to work. But the heuristics is what I want :) 

It seems to be related to `shiftwidth`:
* `set shiftwidth=0`, no suggestions
* `set shiftwidth=4`, proper suggestions

But I fail to see why that is. Should that be added as another error-status or should it work, @monkoose?

**Comment by monkoose** [comment]
`shiftwidth` shouldn't disable codeium. So it is definitely a bug. I have checked it manually and in any buffer where shiftwidth is set to 0 there are no suggestions.

**Comment by monkoose** [comment]
Should be fixed with the last commit.

**Comment by Kypert** [comment]
> Should be fixed with the last commit. @Kypert thanks for the investigation.

Right back at you, thanks for the fix! Verified v1.7.0, I can run with `tpope/vim-sleuth` and get suggestions in my `*.go` files :D
