### ISSUE TITLE
Error: Attempt to concatenate field `stderr`  (a nil value)

### ISSUE THREAD

**Issue by Pheon-Dev** [monkoose/neocodeium#7]
### 👎 Problem

When running `NeoCodeium auth`, it produces an error and does not allow me to paste the copied token
![Picture](https://github.com/monkoose/neocodeium/assets/93865776/afd602fe-ad73-443f-a2f2-7dc5ecc9708d)

### 🔢 Steps to reproduce
```bash
nvim --clean
```
```lua
:set rtp+=~/.local/share/nvim/lazy/neocodeium
:lua require('neocodeium').setup()
:lua vim.keymap.set('i', '', function() require('neocodeium').accept() end)
```

![Picture_1](https://github.com/monkoose/neocodeium/assets/93865776/f4c0e1d4-a8ed-4ceb-ba5c-852136635335)

### 👍 Expected behavior

To allow me to paste the copied token

### Neovim version (nvim -v)

nightly

### Operating system (uname -om)

Linux x86_64

### :checkhealth neocodeium

OK

### Relevant log output

```shell
`NeoCodeium: log file is empty`
```

**Comment by monkoose** [comment]
Hello, thanks for reporting. 

Is browser opened for you automatically?

**Comment by monkoose** [comment]
Can you help me with debugging? 

If so, please find the location of the NeoCodeium in your system and add to `lua/NeoCodeium/commands.lua` at line 25:
```lua
vim.print(obj)
```
Dave, open fresh nvim and try to auth and paste output of `:mes`

**Comment by monkoose** [comment]
Should be fixed with last commit.

**Comment by Pheon-Dev** [comment]
> Should be fixed with last commit.

Thanks, it's working alright now.

**Comment by monkoose** [comment]
> after adding that line to commands.lua

This is weird. Internally it uses `:h vim.ui.open()` which is returned `vim.SystemCompleted` type, which is a table with can be found at the end of `:h vim.system()`
```lua
{
  code = ...,
  signal = ...,
  stdout = ...,
  stderr = ...,
}
```

And for me it returns such table.

**Comment by Pheon-Dev** [comment]
I haven't dug deep into it but it works alright now. Just fiddling with the keybinds now to suit my workflow. I had a bit of trouble after auth but got fixed once I (re)moved `~/.codeium` folder as it would not edit the `config.json` file to add the token[NOTE: to those who have both `codeium` and `neocodeium`]. Either way it works well now, not unless someone else encounters a similar problem then I'll chime in to help where I can. Thanks.
